### ISSUE TITLE
Causes "bumpy" gutters

### ISSUE THREAD

**Issue by paradox460** [AtomLinter/Linter#410]
When a line has a warning, info, or error, it "bumps" the number over a few pixels.

![image](https://cloud.githubusercontent.com/assets/168193/6030662/db380610-abad-11e4-9d70-0faf26c10769.png)

From what I can tell, its because the font-size is set to 1.1em, although setting a fixed-width for the gutter icons solves this issue, like so:

```less
.line-number .icon-right {
  width: 10px;
}
```

Might be due to breaking changes in atom?
